codecov:
  require_ci_to_pass: true

comment:
  layout: "condensed_header, diff, flags"
  behavior: default
  require_changes: true
  hide_project_coverage: false

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        base: 90%
        if_no_uploads: error
        informational: false
        only_pulls: true
    
    patch:
      default:
        target: 80%
        threshold: 0%
        if_no_uploads: error
        informational: false